### ISSUE TITLE
To-do📝

### ISSUE THREAD

**Issue by PriskaSama** [PriskaSama/maze-bank#1]
- [ ] Retirer logo nav bar
- [ ] bg img a modifier 
- [ ] Font size a vérifier (concordance)
- [ ] Bouttons : en col ou row (dépôt + retrait)
- [ ] Padding + margin à rechecker
- [ ] Center le label input (virement) + font size à vérifier
- [ ] **Footer** : font size
- [ ] **Version mobile** : padding des bouttons
- [ ] Ajouter animation pour l'image de la galaxie
- [ ] JAVASCRIPT => algo à terminer
